name: mlenv
dependencies:
  
- ipython
- ipykernel
- nltk
- numpy
- pymc3
- scikit-learn
- scipy
- seaborn
- statsmodels
- tensorflow
- pip
- pip:
  - simpledbf
  - missingno
  - jupyterlab
  - shap
  - geopandas
  - pyogrio
  - git+https://github.com/pysal/libpysal.git
  - pytables
  - sqlalchemy
  - openpyxl
  - catboost
  - xgboost
  - lightgbm
