# Home Directory


# Directories


## Filenames
# Input Files

# Variable Names
date_time_col : ''
predictor_name : 'SalePrice'

# Output Files


# Training File config
cross_val_strategy : 'k-fold'
n_splits : 10




 